//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace CustomerSystem.Backend.Models
{
	/// <summary>
	/// Database       : example
	/// Data Source    : example
	/// Server Version : 3.46.1
	/// </summary>
	public partial class DbContext : LinqToDB.Data.DataConnection
	{
		#region Tables

		public ITable<UserInfo> UserInfo { get { return this.GetTable<UserInfo>(); } }

		#endregion

		#region .ctor

		public DbContext()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DbContext(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DbContext(DataOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DbContext(DataOptions<DbContext> options)
			: base(options.Options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();

		#endregion
	}

	[Table("UserInfo")]
	public partial class UserInfo
	{
		[Column, Nullable] public long?  Id       { get; set; } // integer
		[Column, Nullable] public string Username { get; set; } // text(max)
		[Column, Nullable] public string Password { get; set; } // text(max)
	}
}
